#!/bin/sh
if [ $# -ne 2 ];
then
    echo zbyt mało argumentów
    exit 1
fi
echo z uzyciem operatora:
echo $(($1**$2))

result=1
for (( i=0; i<$2; i++ ))
do
    ((result=result*$1))
done
echo przy uzyciu pętli:
echo $result